CREATE TABLE TASKS (
  id BIGINT NOT NULL AUTO_INCREMENT  PRIMARY KEY,
  task_name VARCHAR(250) NOT NULL,
  task_group VARCHAR(250) NOT NULL,
  time_spent VARCHAR(250) NOT NULL,
  assignee VARCHAR(250) NOT NULL,
  complete_status BOOLEAN NOT NULL
);
CREATE TABLE SUBTASKS (
  id BIGINT NOT NULL AUTO_INCREMENT  PRIMARY KEY,
  sub_task_name VARCHAR(250) NOT NULL,
  task_id BIGINT NOT NULL,
  task_group VARCHAR(250) NOT NULL,
  time_spent VARCHAR(250) NOT NULL,
  assignee VARCHAR(250) NOT NULL,
  complete_status BOOLEAN NOT NULL
);